apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: data-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'fastapi'
        static_configs:
          - targets: ['fastapi:8001']
      - job_name: 'databricks-exporter'
        static_configs:
          - targets: ['databricks-exporter:8000']
