apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt
  namespace: data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt
  template:
    metadata:
      labels:
        app: dbt
    spec:
      containers:
      - name: dbt
        image: dbt:latest
        command: ["sleep", "infinity"]
        env:
          - name: DATABRICKS_TOKEN
            valueFrom:
              secretKeyRef:
                name: databricks-secrets
                key: DATABRICKS_TOKEN
          - name: DATABRICKS_HOST
            valueFrom:
              secretKeyRef:
                name: databricks-secrets
                key: DATABRICKS_HOST
