global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8001']

  - job_name: 'dbt'
    static_configs:
      - targets: ['dbt:8000']

  # (Optional) if you have a Databricks metrics exporter container:
  - job_name: 'databricks'
    static_configs:
      - targets: ['databricks-exporter:8080']



