global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "airflow"
    static_configs:
      - targets: ["statsd-exporter:9102"]

  - job_name: "databricks"
    static_configs:
      - targets: ["databricks-exporter:8000"]
